version: '3'
services:
  web:
    build: .
    ports:
    - "80:80"
    volumes:
    - .:/code
    - .:/usr/share/nginx/html
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
